enabledFeatures = [
    # dev-mode # Enabling developer config from file `dev-mode.conf`
    # auth # Needs Hoplite decoder for DirectSerializedKey — enable once fixed
    wallet2-persistence # Enable SQL persistence (SQLite/Postgres)
]
disabledFeatures = [
    # ...
]
